### ISSUE TITLE
Support for Wifi LAN / ZeroConf / Bonjour?

### ISSUE THREAD

**Issue by n8fr8** [sabzo/ayanda#3]
Wifi Direct is great, but in the past, we've found that just finding peers on a LAN network who are speaking zeroconf/bonjour can work quite well. This also can work with one device running a wifi hotspot, and others connecting to it.

Can we support that feature here? LibNearbyShare has some code already for it.

**Comment by sabzo** [comment]
+1 @n8fr8 good point! I've added LAN discovery on this branch https://github.com/sabzo/ayanda/tree/feature/add_lan.

I'll be merging this in soon.

**Comment by sabzo** [comment]
LAN discovery was added.
