### ISSUE TITLE
Add ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by pprathameshmore** [sabzo/ayanda#39]
## Description
As a developer,
I need to add ISSUE_TEMPLATE.md,
so that we have a proper issue template.

## Mocks
![issue](https://user-images.githubusercontent.com/17108186/54588372-cf728380-4a48-11e9-9e3f-e2d08374aa6e.jpg)

### Update [Required]
- [x] Add ISSUE_TEMPLATE.md
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours 

@sabzo I would like to work on this issue.

**Comment by sabzo** [comment]
@pprathameshmore Not a real issue. Overly formal. Please select an existing issue.

**Comment by pprathameshmore** [comment]
@sabzo Okay!
