### ISSUE TITLE
GitHub repository as dependency to android projects

### ISSUE THREAD

**Issue by pprathameshmore** [sabzo/ayanda#43]
@sabzo Currently we can't use this repository as a dependency in Android projects. We should pack this library using https://jitpack.io/

**Comment by somenath1435** [comment]
@sabzo 
I've packed the library in https://jitpack.io/
output:
dependencies {
	        implementation 'com.github.sabzo:ayanda:-4bdf1d1593-1'
	}
please suggest what to do next

**Comment by somenath1435** [comment]
There are currently 3 versions of library available in jitpack
![Screenshot (1)](https://user-images.githubusercontent.com/43093724/56086022-8fe26000-5e6b-11e9-8437-ebb66e148f21.png)

**Comment by pprathameshmore** [comment]
@somenath1435 First ask a maintainer @sabzo
